### PR TITLE
Branch mf

### PR DESCRIPTION
**Pull request by mbfons**
Hi Jonny, this includes:
- 'Thinking' post on online consultations
- Adding my profile to 'Team'
- Amendment in authoring of the PHM risk strat git project
- Adding the nhsx-publications project to 'projects'
- Slightly amending 'How-to' for windows
- Gemfile : had to add a line for it to work in windows: `gem 'wdm', '>= 0.1.0'` (possibly worth checking it this impacts mac serve)
Managed to preview with ruby/kejyll/bundle and it looked overall fine configuration-wise
Thanks!

### CODE REVIEW

**Review by JRPearson500 — COMMENTED** [review]
Reduce spacing at start.
Centre align figures using html
Use markdown for table rather than html.

**Comment by mbfons** [comment]
Thanks @JRPearson500 , I've actioned the changes and removed the second gemfile.

**Comment by craig-shenton** [comment]
Might be another way to do the tables. 

| Group | Characteristic | Overall | Had any GP consultation | Had OC coding instance |
| :------------- | :------------- | :--------- | :---------- | :----------- |
|Count|Total|N = 20,651,036|N = 17,166,765|N = 1,087,919|
|**Sex**|Female|9,599,496 (49%)|9,172,833 (53%)|661,235 (61%)|
|**Sex**|Male|9,963,322 (51%)|7,993,645 (47%)|426,654 (39%)|
|**Sex**|Other/Unknown|299 (<0.1%)|287 (<0.1%)|30 (<0.1%)|
|**Age**|Total|41 (21, 59)|44 (24, 61)|43 (27, 58)|
|**Age group**|(0,18]|4,151,378 (21%)|3,279,485 (19%)|147,313 (14%)|
|**Age group**|(18,40]|5,388,980 (28%)|4,295,711 (25%)|349,162 (32%)|
|**Age group**|(40,50]|2,665,869 (14%)|2,353,934 (14%)|176,261 (16%)|
|**Age group**|(50,60]|2,735,067 (14%)|2,577,374 (15%)|178,461 (17%)|
|**Age group**|(60,70]|2,144,742 (11%)|2,137,624 (13%)|124,470 (12%)|
|**Age group**|(70,80]|1,598,702 (8.2%)|1,627,530 (9.6%)|74,886 (6.9%)|
|**Age group**|(80,Inf]|716,706 (3.7%)|729,284 (4.3%)|30,036 (2.8%)|
|**Age group**|Unknown|161,673|165,823|7,330|
```
| Group | Characteristic | Overall | Had any GP consultation | Had OC coding instance |
| :------------- | :------------- | :--------- | :---------- | :----------- |
|Count|Total|N = 20,651,036|N = 17,166,765|N = 1,087,919|
|**Sex**|Female|9,599,496 (49%)|9,172,833 (53%)|661,235 (61%)|
|**Sex**|Male|9,963,322 (51%)|7,993,645 (47%)|426,654 (39%)|
|**Sex**|Other/Unknown|299 (<0.1%)|287 (<0.1%)|30 (<0.1%)|
|**Age**|Total|41 (21, 59)|44 (24, 61)|43 (27, 58)|
|**Age group**|(0,18]|4,151,378 (21%)|3,279,485 (19%)|147,313 (14%)|
|**Age group**|(18,40]|5,388,980 (28%)|4,295,711 (25%)|349,162 (32%)|
|**Age group**|(40,50]|2,665,869 (14%)|2,353,934 (14%)|176,261 (16%)|
|**Age group**|(50,60]|2,735,067 (14%)|2,577,374 (15%)|178,461 (17%)|
|**Age group**|(60,70]|2,144,742 (11%)|2,137,624 (13%)|124,470 (12%)|
|**Age group**|(70,80]|1,598,702 (8.2%)|1,627,530 (9.6%)|74,886 (6.9%)|
|**Age group**|(80,Inf]|716,706 (3.7%)|729,284 (4.3%)|30,036 (2.8%)|
|**Age group**|Unknown|161,673|165,823|7,330|
```

**Comment by mbfons** [comment]
thanks @craig-shenton , I've adapted the table based on your suggestions, except for the repeat of the Group header in all lines, for readability :)

@JRPearson500 , ready for review.

Thank you both!

**Review by JRPearson500 — APPROVED** [review]

**Pull request merged**
